[OCF-63] runtime/action-python-2: Switch to CentOS 7
projectodd/openwhisk-openshift pull request #10
Opened 2018-03-20 12:36 UTC by goldmann

https://issues.jboss.org/browse/OCF-63

2018-03-21 08:31 UTC, goldmann commented
I'm not sure why the test failed, but I do see similar failures in my local environment, even with the original image.

2018-03-21 15:54 UTC, jcrossley3 requested changes

2018-03-21 15:54 UTC, jcrossley3 commented on docker/runtimes/action-python-2/Dockerfile
> +FROM jboss/base:latest
I don't love latest here

2018-03-22 09:50 UTC, goldmann commented
@jcrossley3 This one is ready

2018-03-22 12:41 UTC, jcrossley3 commented on docker/runtimes/action-python-2/Dockerfile
> +FROM jboss/base@sha256:39bcf23f34ca58db0769121674d2a82aa4ea2ae9c956e280cb0ba1ef64c68b51
Now *THAT* looks pretty specific! Thanks!

2018-03-22 12:42 UTC, jcrossley3 approved these changes

2018-03-22 12:42 UTC, merged